### ISSUE TITLE
Hi! Thanks for your great work. But I try to run your release code, and there are something wrong about 'tutils'.  Could you tell me how I install this pkg?

### ISSUE THREAD

**Issue by BossZard** [Curli-quan/Slide-SAM#1]
Hi! Thanks for your great work. But I try to run your release code, and there are something wrong about 'tutils'.  Could you tell me how I install this pkg?

**Comment by Curli-quan** [comment]
Thank you for pointing out my problem. Please try ``pip install trans-utils'' to install it.
